name: Go RSS Feed Crawler

on:
    push:
        branches: ["main"] # 브랜치가 main일 때만 동작하도록 설정
    schedule:
        - cron: '0 0 * * *' # 매일 00:00 UTC에 동작하도록 설정

jobs:
    update_readme:
        runs-on: ubuntu-latest # 우분투에서 동작하도록 설정
        steps:
        - uses: actions/checkout@v3 # 깃허브 액션에서 제공하는 checkout 액션 사용

        - name: Set up Go
          uses: actions/setup-go@v4 # 깃허브 액션에서 제공하는 Go 설정 액션 사용
          with:
            go-version: '1.21' # Go 1.21 버전 사용
        
        - name: Get dependencies
          run: go get -v -t -d ./... # Go 모듈 다운로드
        
        - name: Run Go
          run: go run main.go # Go 코드 실행

        - name: Push README.md
          run: | # README.md 파일을 커밋하고 푸시하는 과정
            git config --local user.name 'Lee Hyohwak'
            git config --global user.email 'crewe1746@naver.com'
            git add README.md
            git commit -m "Update README.md"
            git push